ai_automator.ai_automator.*:
  type: config_entity
  label: AI Automator
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
