provider_huggingface.settings:
  type: mapping
  label: 'Huggingface AI Settings'
  mapping:
    api_key:
      type: string
      label: 'API Key'
      required: true
    models:
      type: mapping
      label: 'Models'
      required: false
      mapping:
        chat:
          type: sequence
          label: 'Model'
          required: false
          sequence:
            type: string
        embeddings:
          type: sequence
          label: 'Model'
          required: false
          sequence:
            type: string
        image_classification:
          type: sequence
          label: 'Model'
          required: false
          sequence:
            type: string
