site_name: Documentation for AI (Artificial Intelligence) module for Drupal
theme:
  name: material
nav:
  - Home: index.md
  - Develop & Contribute:
    - Getting Started: developers/developer_information.md
    - Why base on the AI module?: developers/why_ai.md
    - Making AI Calls:
      - The Idea: developers/base_calls.md
      - Chat Call: developers/call_chat.md
      - Text-To-Image Call: developers/call_text_to_image.md
      - Text-To-Speech Call: developers/call_text_to_speech.md
      - Speech-To-Text Call: developers/call_speech_to_text.md
      - Embeddings Call: developers/call_embeddings.md
      - Moderation Call: developers/call_moderation.md
      - Audio-To-Audio Call: developers/call_audio_to_audio.md
      - Speech-To-Speech Call: developers/call_speech_to_speech.md
      - Image Classification Call: developers/call_image_classification.md
    - Develop an AI Provider: developers/writing_an_ai_provider.md
    - Develop a third-party module: developers/develop_third_party_module.md
    - Contribute to the AI module: developers/contribute.md
    - Events: developers/events.md
  - Modules:
    - AI Providers:
      - Ollama: modules/providers/provider_ollama/index.md
    - VDB Providers:
      - Milvus: modules/vdb_providers/vdb_provider_milvus/index.md
    - AI Content: modules/ai_content/index.md
    - AI Automators: modules/ai_automator/index.md

docs_dir: docs
site_dir: site
